### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by kthjm**
tiny PR about [`hast-to-hyperscript@4.0.0`](https://github.com/syntax-tree/hast-to-hyperscript/releases/tag/4.0.0)

### CODE REVIEW

**Comment by rhysd** [comment]
Could you describe why you want to update the dependency?

**Comment by kthjm** [comment]
Because `4.0.0` can cope better the issue that "attribute case in React".
https://github.com/syntax-tree/hast-to-hyperscript/pull/8
I thought this major upgrade is important for `rehype-react` 😺.

**Comment by rhysd** [comment]
Sure. Thank you.

**Comment by rhysd** [comment]
This change was included in v3.0.2.

**Pull request merged**
